### ISSUE TITLE
Impossible to install elm-ui under ubuntu 15.10

### ISSUE THREAD

**Issue by Sinouplen** [gdotdesign/elm-ui#16]
Hi,

When I tried to install elm-ui (Modification with `sudo` before command line)
`npm install elm-ui -g`

I have those errors:
`> intern@3.0.6 install /usr/lib/node_modules/elm-ui/node_modules/intern

> node support/fixdeps.js

fs.js:945
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EACCES: permission denied, symlink '/usr/lib/node_modules/elm-ui/node_modules/dojo' -> '/usr/lib/node_modules/elm-ui/node_modules/intern/node_modules/dojo'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at /usr/lib/node_modules/elm-ui/node_modules/intern/support/fixdeps.js:33:6
    at Array.forEach (native)
    at Object.<anonymous> (/usr/lib/node_modules/elm-ui/node_modules/intern/support/fixdeps.js:14:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
/usr/lib
└── (empty)

npm WARN optional Skipping failed optional dependency /elm-ui/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "elm-ui" "-g"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! intern@3.0.6 install: `node support/fixdeps.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the intern@3.0.6 install script 'node support/fixdeps.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the intern package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node support/fixdeps.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs intern
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls intern
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gael/Projets/elm/npm-debug.log
npm ERR! code 1
`

We can found the complete log files of npm
[npm-debug.log.zip](https://github.com/gdotdesign/elm-ui/files/148048/npm-debug.log.zip)

Thanks for your help.

**Comment by gdotdesign** [comment]
Hey, it seems like you don't have root access can you try to run it with `sudo` (`sudo npm install elm-ui -g`)?

**Comment by Sinouplen** [comment]
I launch it with `sudo` and I have those error.

**Comment by gdotdesign** [comment]
I have pushed a new version (0.1.4) out. I moved some not needed dependencies like **intern** which caused your error, hopefully this will fix it.

**Comment by Sinouplen** [comment]
Hi,
It's OK now, I can installed it on ubuntu.
Thanks a lot.
