### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by gdotdesign** [gdotdesign/elm-ui#27]
Windows binaries are living in an other directories then the unix ones, and we need to find the right one.

**Comment by ademets** [comment]
I tried running elm-ui via a npm install under Windows. Following the tutorial, `elm-ui server` crashes, as soon as i call `localhost:8001` in my browser - it does start up, though.
Terminal output:
`
Error: spawn C:\Users\ademe\AppData\Roaming\npm\node_modules\elm-ui\node_modules\elm\binwrappers\elm-make ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

`elm-ui build` causes the same exception.

**Comment by gdotdesign** [comment]
Elm-UI will use _npm-which_ from the next version, which hopefully will resolve this issue.
The commit is here: https://github.com/gdotdesign/elm-ui/commit/398b22449b0b60175bbc2750f51425c1a4d77255

**Comment by gdotdesign** [comment]
I'm closing this since I just released 1.0.0 which moves the development environment functionality to https://github.com/gdotdesign/elm-dev-env. If the problem persist please open an issue there.
