### ISSUE TITLE
Is there a way to rebuild files on change?

### ISSUE THREAD

**Issue by AlexKovalevych** [gdotdesign/elm-ui#34]
Something like `elm-build --watch` so js will rebuid each time elm files in `source` directory change

**Comment by gdotdesign** [comment]
Currently there is no command for that.

Elm-UI uses [Browsersync](https://www.browsersync.io) which means that if you open the specific URL (localhost:8002 by default), the page will be reloaded when files change and CSS will be replaced. 

If you want to create a command for this it would be awesome. You can find the details for the `start / server` command here: https://github.com/gdotdesign/elm-ui/blob/master/bin/lib/command/serve.js

**Comment by gdotdesign** [comment]
I'm closing this since I just released 1.0.0 which removes the requirement of using the `elm-ui` node package, allowing you to add Elm-UI to your build stack just as a normal Elm package.
