### ISSUE TITLE
elm-ui install version constraint failure

### ISSUE THREAD

**Issue by chancyk** [gdotdesign/elm-ui#36]
I'm getting the following error when trying to use `elm-ui install`:

Resolving versions...
error { '0': [Error: Unable to satisfy version constraint: gdotdesign/elm-ui@>=0.4.0 <1.0.0 from root] }

**Comment by gdotdesign** [comment]
Elm-UI uses  https://github.com/gdotdesign/elm-github-install to install dependencies, and there can be a number of reasons that installation can fail:
* there is no git installed on your system
* Github was not available at the time

Can you post your `elm-package.json` file and provide some information about your OS and system?

**Comment by chancyk** [comment]
I'm on Windows 7 and Windows 10.

I got a more verbose error message by executing `elm-ui install` under the bash prompt that installs with Git instead of the Window's command prompt:

```bash
$ elm-ui install
Resolving versions...
Starting downloads...

 ● elm-lang/mouse - 1.0.1
fs.js:681
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EPERM: operation not permitted, rename 'C:\Projects\elm\elm-ui-test\elm-stuff\packages\elm-community\maybe-extra\maybe-extra-3.0.0' -> 'C:\Projects\elm\elm-ui-test\elm-stuff\packages\elm-community\maybe-extra\3.0.0'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)
```

This lead me to this issue https://github.com/Medium/phantomjs/issues/19 for phantomjs which people were solving by disabling their Antivirus software that was misbehaving with Node, and disabling my AV does in fact solve the problem!

So it might be worth mentioning the AV issue in the install guide for us silly Windows users with overbearing and silently sabotaging AV software. : )
