### ISSUE TITLE
Elm ui setup does not handle whitespace in path?

### ISSUE THREAD

**Issue by peterhartman** [gdotdesign/elm-ui#39]
When I follow the instructions on the homepage (http://elm-ui.info/)

I get the following error:
"You have errors in of your Elm file(s):
elm-make: /Users/phartman/Documents/OneDrive: openFile: does not exist (No such file or directory)"

Where OneDrive is the first part of a directory name containing whitespace.

**Comment by gdotdesign** [comment]
Probably this is a bug here https://github.com/gdotdesign/elm-ui/blob/master/bin/lib/render/elm.js#L19, as the `filename` is not quoted.

It should be a pretty quick fix, when I have some time I'll do it, thanks for reporting!

**Comment by gdotdesign** [comment]
Fixed in 0.4.2 https://github.com/gdotdesign/elm-ui/releases/tag/0.4.2
