### ISSUE TITLE
version of Elm?

### ISSUE THREAD

**Issue by ghost** [gdotdesign/elm-ui#40]
which version(s) of Elm are you using for this and are there updates to elm-ui when there are updates to the elm architecture? I think 0.18 has some changes that may affect the lib? I'm mainly curious to know if I can use this with 0.17.x

thanks!

**Comment by gdotdesign** [comment]
I started it on 0.16 but only released it on 0.17 (versions up to 0.3.x), and it's updated to 0.18 with version 0.4.x.

I'm planning to update it for every new version for the foreseeable future, and you can always check the Elm version it's using from the [`package.json`](https://github.com/gdotdesign/elm-ui/blob/master/package.json#L40).

**Comment by ghost** [comment]
awesome, that's helpful, I just thought it would be nice to have a list in the README covering that; 0.x => elm 0.x, 0.x+1 => elm 0.x+1, etc.
