### ISSUE TITLE
How does this works in production ?

### ISSUE THREAD

**Issue by pyladune** [gdotdesign/elm-ui#48]
Should we use a elm-ui server for production too ? Thanks

**Comment by gdotdesign** [comment]
There is a command `elm-ui build` which builds all files (JS, HTML and CSS) for production into `./dist`, so the intended way is to serve them as static files with something (ngnix, apache, S3).

**Comment by mrozbarry** [comment]
@gdotdesign does this also compile the icons in, or do I need to import them separately in production?

**Comment by gdotdesign** [comment]
If you referring to `Ui.icon` and the ones that components use It compiles them as well.

**Comment by gdotdesign** [comment]
I'm closing this since I just released 1.0.0 which moves the development environment functionality to https://github.com/gdotdesign/elm-dev-env.
