### ISSUE TITLE
KitchenSink demo in Webkit\Safari

### ISSUE THREAD

**Issue by gothy** [gdotdesign/elm-ui#5]
Please check out how Elm UI demo works in webkit. Feels very slow on both mobile and on desktop.
Also dropdowns and few other widgets doesn't seem to work.

Thanks for your work! :) :+1:

**Comment by gdotdesign** [comment]
Thanks for the bug report! 

I'll look into the bugs and as for the slowness it's not really optimized yet, also the it does a lot of unnecessary calculations (create records for read-only and disabled states on every change resulting in re-rendering everything) so it's not representative of a real like app.

**Comment by gothy** [comment]
Dropdowns are working now. Cool :)

However playing with the demo in Safari is not just slow, it crashes the Safari tab in just two minutes of "clicking all the things"

**Comment by gdotdesign** [comment]
I just deployed an optimized version of KitchenSink, the average render time per frame is now **~ 2ms** down from **~ 15ms** (for me in chrome), can you check it if there is improvement for you?

**Comment by gothy** [comment]
Not really :( You should try it yourself to feel the difference between chrome and safari. It's drastic

Also, something is wrong with css after update, since Calendar now looks like this ![](http://take.ms/V0ojS)
and this is how it looks on localhost before pull ![](http://take.ms/MSi5V)

Made a video on all issues I've found http://take.ms/I0zu3

Tried to fix the issue with Dropdown and make a PR for it but failing so far :)

**Comment by gdotdesign** [comment]
Hey, thanks for all the inputs.

I managed to get my hands on a Safari finally (9. something) and I tracked the junk in scrolling to the **ColorPanel** specifically the gradients in uses. 

You can see the fixes in this commit: 8e67efa3170789e597bb47067a91efe559980fb4.

I pushed a new version of it to gh-pages, If it's good for you too i'll close this issue.

Edit: The Calendar for me was fine in Safari and in Chrome, if you can tell me the version of the Safari you are using I can investigate further.

**Comment by gothy** [comment]
Lags are gone! :+1: :fireworks: 

Safari 8.0.7, I'm still on Yosemite.
