### ISSUE TITLE
`npm start` requires a `config/development.json`, but it doesn't exist in the repo, .gitignore, and no mention in CONTRIBUTING.md

### ISSUE THREAD

**Issue by mrozbarry** [gdotdesign/elm-ui#55]
To work around this, I just added my own config/development.json locally with an empty object, and that was enough to satisfy `npm start`. Is this related to selenium (I didn't install that), or is there something else?

**Comment by gdotdesign** [comment]
It's not required, it just shows that it's not there. Are you getting an error making and the server won't start?

**Comment by mrozbarry** [comment]
Ok, so the server does run, but the terminal reports some errors every refresh. Out of curiousity, what is it for?

**Comment by gdotdesign** [comment]
It's for using environmental variables http://elm-ui.info/documentation/guides/environment-variables

There can one for production, development, staging and on every render it's trying to load it but it's no there so an warning is logged.
