### ISSUE TITLE
Date not being picked in FireFox

### ISSUE THREAD

**Issue by michie1** [gdotdesign/elm-ui#63]
When I go to http://elm-ui.info/reference/date-picker in FireFox 51.0.1 (64-bit) on Ubuntu 16.04 and click on the date field in order to select a new day, the new date is not being picked. Going to another month isn't working either, because it closes the date picker. 
![ui-datepicker-firefox](https://cloud.githubusercontent.com/assets/1347371/23200313/e40464da-f8d3-11e6-9ce8-51e4c3f52560.gif)

**Comment by gdotdesign** [comment]
Thanks for reporting this!

It seems that Firefox handles elements with tabindex differently from other browsers, there is stackoverflow thread about it: http://stackoverflow.com/questions/28772810/in-firefox-click-on-absolute-element-inside-focusable-element-does-not-focus-fo

I'll look into possible solutions soon.

**Comment by gdotdesign** [comment]
Here is the commit that fixes it https://github.com/gdotdesign/elm-ui/commit/bd3e9fd139822d05d8be76d02ca106b6e6625e01. 

I'll leave this issue open until the fix is released with a new version.

**Comment by gdotdesign** [comment]
Released in https://github.com/gdotdesign/elm-ui/releases/tag/1.1.0
