### ISSUE TITLE
Ui.ColorPicker panel disappears inappropriately in Firefox

### ISSUE THREAD

**Issue by crazymykl** [gdotdesign/elm-ui#69]
Steps to reproduce:
- Click on the picker to open it
- Click and drag on either the large grid or the two sliders

The controls are usable so long as the mouse button is held, they just close visually.

**Comment by gdotdesign** [comment]
This was the same issue as https://github.com/gdotdesign/elm-ui/issues/63 which was fixed in 1.1.0 I'm updating the website soon.

**Comment by crazymykl** [comment]
Thanks for the prompt response!

**Comment by crazymykl** [comment]
Validated as working now.
