### ISSUE TITLE
Cannot initialize ColorPicker with a color

### ISSUE THREAD

**Issue by WoozyGoat** [gdotdesign/elm-ui#95]
Documentation says that we can initialize ColorPicker in this way :
`colorPicker = Ui.ColorPicker.init Color.yellow`

But when I tried that, I got this error : 
`
Function `init` is expecting the argument to be:
    ()
But it is:
    Color.Color
`

Is this a bug, or am I doing something wrong?

**Comment by gdotdesign** [comment]
The documentation is wrong in this case.

You can initialize a new `Ui.ColorPicker` with:

```
( colorPicker, cmd ) = 
  Ui.ColorPicker.init ()
  |> Ui.ColorPicker.setValue Color.Yellow
```

**Comment by WoozyGoat** [comment]
Thanks a lot, it works ! I close this issue.
